/* Generated by tools/build-art.cjs. */
#ifndef ALAMEDA_DEPTH_COMPOSITE_H
#define ALAMEDA_DEPTH_COMPOSITE_H
#include <stdint.h>
#define ALAMEDA_DEPTH_COMPOSITE_TILE_COUNT 137u
extern const uint8_t alameda_depth_composite_tiles[2192];
extern const uint8_t alameda_depth_composite_map[240];
extern const uint8_t alameda_depth_composite_attributes[240];
extern const uint16_t alameda_depth_composite_palettes[32];
#endif
