/* Generated by tools/build-art.cjs. */
#ifndef ALAMEDA_DEPTH_H
#define ALAMEDA_DEPTH_H
#include <stdint.h>
#define ALAMEDA_DEPTH_TILE_COUNT 139u
extern const uint8_t alameda_depth_tiles[2224];
extern const uint8_t alameda_depth_map[240];
extern const uint8_t alameda_depth_attributes[240];
extern const uint16_t alameda_depth_palettes[32];
#endif
