/* Generated by tools/build-art.cjs. */
#ifndef ALAMEDA_SCENE_H
#define ALAMEDA_SCENE_H
#include <stdint.h>
#define ALAMEDA_SCENE_TILE_COUNT 126u
extern const uint8_t alameda_scene_tiles[2016];
extern const uint8_t alameda_scene_map[360];
extern const uint8_t alameda_scene_attributes[360];
extern const uint8_t alameda_scene_library_tiles[102];
extern const uint16_t alameda_scene_palettes[32];
#endif
