/* Generated by tools/build-art.cjs. */
#ifndef CAMPUS_LAYERED_H
#define CAMPUS_LAYERED_H
#include <stdint.h>
extern const uint8_t campus_layered_map[360];
extern const uint8_t campus_layered_attributes[360];
extern const uint16_t campus_layered_palettes[32];
#endif
