/* Generated by tools/build-art.cjs. */
#ifndef CAMPUS_SCENE_H
#define CAMPUS_SCENE_H
#include <stdint.h>
#define CAMPUS_SCENE_TILE_COUNT 128u
extern const uint8_t campus_scene_tiles[2048];
extern const uint8_t campus_scene_map[360];
extern const uint8_t campus_scene_attributes[360];
extern const uint8_t campus_scene_library_tiles[102];
extern const uint16_t campus_scene_palettes[32];
#endif
