/* Generated by tools/build-art.cjs. */
#ifndef CAMPUS_DEPTH_H
#define CAMPUS_DEPTH_H
#include <stdint.h>
#define CAMPUS_DEPTH_TILE_COUNT 179u
extern const uint8_t campus_depth_tiles[2864];
extern const uint8_t campus_depth_map[240];
extern const uint8_t campus_depth_attributes[240];
extern const uint16_t campus_depth_palettes[32];
#endif
