/* Generated by tools/build-art.cjs. */
#ifndef CAMPUS_DEPTH_COMPOSITE_H
#define CAMPUS_DEPTH_COMPOSITE_H
#include <stdint.h>
#define CAMPUS_DEPTH_COMPOSITE_TILE_COUNT 178u
extern const uint8_t campus_depth_composite_tiles[2848];
extern const uint8_t campus_depth_composite_map[240];
extern const uint8_t campus_depth_composite_attributes[240];
extern const uint16_t campus_depth_composite_palettes[32];
#endif
