/* Generated by tools/build-art.cjs. */
#ifndef CEREMONY_MEDAL_SCREEN_H
#define CEREMONY_MEDAL_SCREEN_H
#include <stdint.h>
#define CEREMONY_MEDAL_SCREEN_TILE_COUNT 216u
extern const uint8_t ceremony_medal_screen_tiles[3456];
extern const uint8_t ceremony_medal_screen_map[360];
extern const uint8_t ceremony_medal_screen_attributes[360];
extern const uint16_t ceremony_medal_screen_palettes[32];
#endif
