/* Generated by tools/build-art.cjs. */
#ifndef CEREMONY_RESCUE_SCREEN_H
#define CEREMONY_RESCUE_SCREEN_H
#include <stdint.h>
#define CEREMONY_RESCUE_SCREEN_TILE_COUNT 207u
extern const uint8_t ceremony_rescue_screen_tiles[3312];
extern const uint8_t ceremony_rescue_screen_map[360];
extern const uint8_t ceremony_rescue_screen_attributes[360];
extern const uint16_t ceremony_rescue_screen_palettes[32];
#endif
