/* Generated by tools/build-art.cjs. */
#ifndef CEREMONY_FLAG_SCREEN_H
#define CEREMONY_FLAG_SCREEN_H
#include <stdint.h>
#define CEREMONY_FLAG_SCREEN_TILE_COUNT 208u
extern const uint8_t ceremony_flag_screen_tiles[3328];
extern const uint8_t ceremony_flag_screen_map[360];
extern const uint8_t ceremony_flag_screen_attributes[360];
extern const uint16_t ceremony_flag_screen_palettes[32];
#endif
