/* Generated by tools/build-art.cjs. */
#ifndef CONTROLS_SCREEN_H
#define CONTROLS_SCREEN_H
#include <stdint.h>
#define CONTROLS_SCREEN_TILE_COUNT 117u
extern const uint8_t controls_screen_tiles[1872];
extern const uint8_t controls_screen_map[360];
extern const uint8_t controls_screen_attributes[360];
extern const uint16_t controls_screen_palettes[32];
#endif
