/* Generated by tools/build-art.cjs. */
#ifndef DOG_DETAIL_24_H
#define DOG_DETAIL_24_H
#include <stdint.h>
#define DOG_DETAIL_24_TILE_COUNT 144u
extern const uint8_t dog_detail_24_tiles[2304];
extern const uint16_t dog_detail_24_palettes[4];
#endif
