/* Generated by tools/build-art.cjs. */
#ifndef ENDING_SCREEN_H
#define ENDING_SCREEN_H
#include <stdint.h>
#define ENDING_SCREEN_TILE_COUNT 131u
extern const uint8_t ending_screen_tiles[2096];
extern const uint8_t ending_screen_map[360];
extern const uint8_t ending_screen_attributes[360];
extern const uint16_t ending_screen_palettes[32];
#endif
