/* Generated by tools/build-art.cjs. */
#ifndef FONT_H
#define FONT_H
#include <stdint.h>
#define FONT_TILE_COUNT 54u
extern const uint8_t font_tiles[864];
extern const uint8_t font_character_codes[54];
extern const uint16_t font_palettes[4];
#endif
