/* Generated by tools/build-art.cjs. */
#ifndef GAME_OVER_SCREEN_H
#define GAME_OVER_SCREEN_H
#include <stdint.h>
#define GAME_OVER_SCREEN_TILE_COUNT 89u
extern const uint8_t game_over_screen_tiles[1424];
extern const uint8_t game_over_screen_map[360];
extern const uint8_t game_over_screen_attributes[360];
extern const uint16_t game_over_screen_palettes[32];
#endif
