/* Generated by tools/build-art.cjs. */
#ifndef LANGUAGE_SELECT_SCREEN_H
#define LANGUAGE_SELECT_SCREEN_H
#include <stdint.h>
#define LANGUAGE_SELECT_SCREEN_TILE_COUNT 91u
extern const uint8_t language_select_screen_tiles[1456];
extern const uint8_t language_select_screen_map[360];
extern const uint8_t language_select_screen_attributes[360];
extern const uint16_t language_select_screen_palettes[32];
#endif
