/* Generated by tools/build-art.cjs. */
#ifndef MAPOCHO_DEPTH_COMPOSITE_H
#define MAPOCHO_DEPTH_COMPOSITE_H
#include <stdint.h>
#define MAPOCHO_DEPTH_COMPOSITE_TILE_COUNT 156u
extern const uint8_t mapocho_depth_composite_tiles[2496];
extern const uint8_t mapocho_depth_composite_map[240];
extern const uint8_t mapocho_depth_composite_attributes[240];
extern const uint16_t mapocho_depth_composite_palettes[32];
#endif
