/* Generated by tools/build-art.cjs. */
#ifndef MAPOCHO_LAYERED_H
#define MAPOCHO_LAYERED_H
#include <stdint.h>
extern const uint8_t mapocho_layered_map[360];
extern const uint8_t mapocho_layered_attributes[360];
extern const uint16_t mapocho_layered_palettes[32];
#endif
