/* Generated by tools/build-art.cjs. */
#ifndef MONEDA_LAYERED_H
#define MONEDA_LAYERED_H
#include <stdint.h>
extern const uint8_t moneda_layered_map[360];
extern const uint8_t moneda_layered_attributes[360];
extern const uint16_t moneda_layered_palettes[32];
#endif
