/* Generated by tools/build-art.cjs. */
#ifndef MONEDA_DEPTH_H
#define MONEDA_DEPTH_H
#include <stdint.h>
#define MONEDA_DEPTH_TILE_COUNT 210u
extern const uint8_t moneda_depth_tiles[3360];
extern const uint8_t moneda_depth_map[240];
extern const uint8_t moneda_depth_attributes[240];
extern const uint16_t moneda_depth_palettes[32];
#endif
