/* Generated by tools/build-art.cjs. */
#ifndef MONEDA_DEPTH_COMPOSITE_H
#define MONEDA_DEPTH_COMPOSITE_H
#include <stdint.h>
#define MONEDA_DEPTH_COMPOSITE_TILE_COUNT 207u
extern const uint8_t moneda_depth_composite_tiles[3312];
extern const uint8_t moneda_depth_composite_map[240];
extern const uint8_t moneda_depth_composite_attributes[240];
extern const uint16_t moneda_depth_composite_palettes[32];
#endif
