/* Generated by tools/build-art.cjs. */
#ifndef MONEDA_SCENE_H
#define MONEDA_SCENE_H
#include <stdint.h>
#define MONEDA_SCENE_TILE_COUNT 126u
extern const uint8_t moneda_scene_tiles[2016];
extern const uint8_t moneda_scene_map[360];
extern const uint8_t moneda_scene_attributes[360];
extern const uint8_t moneda_scene_library_tiles[102];
extern const uint16_t moneda_scene_palettes[32];
#endif
