/* Generated by tools/build-art.cjs. */
#ifndef PAUSE_SCREEN_H
#define PAUSE_SCREEN_H
#include <stdint.h>
#define PAUSE_SCREEN_TILE_COUNT 82u
extern const uint8_t pause_screen_tiles[1312];
extern const uint8_t pause_screen_map[360];
extern const uint8_t pause_screen_attributes[360];
extern const uint16_t pause_screen_palettes[32];
#endif
