/* Generated by tools/build-art.cjs. */
#ifndef PLAZA_SCENE_H
#define PLAZA_SCENE_H
#include <stdint.h>
#define PLAZA_SCENE_TILE_COUNT 125u
extern const uint8_t plaza_scene_tiles[2000];
extern const uint8_t plaza_scene_map[360];
extern const uint8_t plaza_scene_attributes[360];
extern const uint8_t plaza_scene_library_tiles[102];
extern const uint16_t plaza_scene_palettes[32];
#endif
