/* Generated by tools/build-art.cjs. */
#ifndef PLAZA_LAYERED_H
#define PLAZA_LAYERED_H
#include <stdint.h>
extern const uint8_t plaza_layered_map[360];
extern const uint8_t plaza_layered_attributes[360];
extern const uint16_t plaza_layered_palettes[32];
#endif
