/* Generated by tools/build-art.cjs. */
#ifndef PLAZA_DEPTH_COMPOSITE_H
#define PLAZA_DEPTH_COMPOSITE_H
#include <stdint.h>
#define PLAZA_DEPTH_COMPOSITE_TILE_COUNT 174u
extern const uint8_t plaza_depth_composite_tiles[2784];
extern const uint8_t plaza_depth_composite_map[240];
extern const uint8_t plaza_depth_composite_attributes[240];
extern const uint16_t plaza_depth_composite_palettes[32];
#endif
