/* Generated by tools/build-art.cjs. */
#ifndef PLAZA_DEPTH_H
#define PLAZA_DEPTH_H
#include <stdint.h>
#define PLAZA_DEPTH_TILE_COUNT 176u
extern const uint8_t plaza_depth_tiles[2816];
extern const uint8_t plaza_depth_map[240];
extern const uint8_t plaza_depth_attributes[240];
extern const uint16_t plaza_depth_palettes[32];
#endif
