/* Generated by tools/build-art.cjs. */
#ifndef PRESIDENTIAL_STANDARD_H
#define PRESIDENTIAL_STANDARD_H
#include <stdint.h>
#define PRESIDENTIAL_STANDARD_TILE_COUNT 12u
extern const uint8_t presidential_standard_tiles[192];
extern const uint8_t presidential_standard_map[12];
extern const uint8_t presidential_standard_attributes[12];
extern const uint16_t presidential_standard_palettes[32];
#endif
