/* Generated by tools/build-art.cjs. */
#ifndef SPRITES_H
#define SPRITES_H
#include <stdint.h>
#define SPRITES_TILE_COUNT 117u
extern const uint8_t sprites_tiles[1872];
extern const uint8_t sprites_frame_tiles[128];
extern const uint8_t sprites_frame_palettes[32];
extern const uint8_t sprites_icon_tiles[3];
extern const uint8_t sprites_icon_palettes[3];
extern const uint16_t sprites_palettes[32];
#endif
