/* Generated by tools/build-art.cjs. */
#ifndef STAGE_CLEAR_SCREEN_H
#define STAGE_CLEAR_SCREEN_H
#include <stdint.h>
#define STAGE_CLEAR_SCREEN_TILE_COUNT 98u
extern const uint8_t stage_clear_screen_tiles[1568];
extern const uint8_t stage_clear_screen_map[360];
extern const uint8_t stage_clear_screen_attributes[360];
extern const uint16_t stage_clear_screen_palettes[32];
#endif
