/* Generated by tools/build-art.cjs. */
#ifndef TITLE_SCREEN_H
#define TITLE_SCREEN_H
#include <stdint.h>
#define TITLE_SCREEN_TILE_COUNT 223u
extern const uint8_t title_screen_tiles[3568];
extern const uint8_t title_screen_map[360];
extern const uint8_t title_screen_attributes[360];
extern const uint8_t title_screen_blink_map[360];
extern const uint8_t title_screen_blink_attributes[360];
extern const uint16_t title_screen_palettes[32];
#endif
