/* Generated by tools/build-art.cjs. */
#ifndef WORLD_MAP_3_SCREEN_H
#define WORLD_MAP_3_SCREEN_H
#include <stdint.h>
#define WORLD_MAP_3_SCREEN_TILE_COUNT 247u
extern const uint8_t world_map_3_screen_tiles[3952];
extern const uint8_t world_map_3_screen_map[360];
extern const uint8_t world_map_3_screen_attributes[360];
extern const uint16_t world_map_3_screen_palettes[32];
#endif
