/* Generated by tools/build-art.cjs. */
#ifndef WORLD_MAP_2_SCREEN_H
#define WORLD_MAP_2_SCREEN_H
#include <stdint.h>
#define WORLD_MAP_2_SCREEN_TILE_COUNT 240u
extern const uint8_t world_map_2_screen_tiles[3840];
extern const uint8_t world_map_2_screen_map[360];
extern const uint8_t world_map_2_screen_attributes[360];
extern const uint16_t world_map_2_screen_palettes[32];
#endif
