/* Generated by tools/build-art.cjs. */
#ifndef WORLD_MAP_4_SCREEN_H
#define WORLD_MAP_4_SCREEN_H
#include <stdint.h>
#define WORLD_MAP_4_SCREEN_TILE_COUNT 239u
extern const uint8_t world_map_4_screen_tiles[3824];
extern const uint8_t world_map_4_screen_map[360];
extern const uint8_t world_map_4_screen_attributes[360];
extern const uint16_t world_map_4_screen_palettes[32];
#endif
