/* Generated by tools/build-art.cjs. */
#ifndef WORLD_MAP_5_SCREEN_H
#define WORLD_MAP_5_SCREEN_H
#include <stdint.h>
#define WORLD_MAP_5_SCREEN_TILE_COUNT 246u
extern const uint8_t world_map_5_screen_tiles[3936];
extern const uint8_t world_map_5_screen_map[360];
extern const uint8_t world_map_5_screen_attributes[360];
extern const uint16_t world_map_5_screen_palettes[32];
#endif
